class Instruction:
    instructions = {
        'iconst_0': 1, 'iconst_1': 1, 'iconst_2': 1, 'iconst_3': 1,
        'iconst_4': 1, 'iconst_5': 1, 'iconst_m1': 1,
        'fconst_0': 1, 'fconst_1': 1, 'fconst_2': 1, 'aconst_null': 1,
        'bipush': 1, 'sipush': 1, 'ldc': 1,
        'iload_0': 1, 'iload_1': 1, 'iload_2': 1, 'iload_3': 1,
        'fload_0': 1, 'fload_1': 1, 'fload_2': 1, 'fload_3': 1,
        'aload_0': 1, 'aload_1': 1, 'aload_2': 1, 'aload_3': 1,
        'lload_0': 2, 'lload_1': 2, 'lload_2': 2, 'lload_3': 2,
        'iload': 1, 'fload': 1, 'aload': 1,
        'getstatic': 1, 'getfield': 0,
        'istore_0': -1, 'istore_1': -1, 'istore_2': -1, 'istore_3': -1,
        'fstore_0': -1, 'fstore_1': -1, 'fstore_2': -1, 'fstore_3': -1,
        'astore_0': -1, 'astore_1': -1, 'astore_2': -1, 'astore_3': -1,
        'lstore_0': -2, 'lstore_1': -2, 'lstore_2': -2, 'lstore_3': -2,
        'istore': -1, 'fstore': -1, 'astore': -1,
        'putstatic': -1, 'putfield': -2,
        'pop': -1, 'swap': 0, 'dup': 1, 'dup_x1': 1, 'dup_x2': 1,
        'iadd': -1, 'fadd': -1, 'isub': -1, 'fsub': -1, 'imul': -1, 'fmul': -1,
        'idiv': -1, 'fdiv': -1, 'irem': -1, 'frem': -1, 'ineg': 0, 'fneg': 0,
        'iinc': 0, 'iand': -1, 'ior': -1, 'ixor': -1,
        'i2f': 0, 'i2c': 0, 'i2d': 0, 'f2i': 0, 'f2d': 0, 'd2f': 0,
        'checkcast': 0,
        'new': 1, 'newarray': 0, 'anewarray': 0, 'multianewarray': 0,'iaload': -1, 'faload': -1, 'baload': -1, 'caload': -1, 'aaload': -1,
        'iastore': -3, 'fastore': -3, 'bastore': -3, 'castore': -3, 'aastore': -3,
        'ifeq': -1, 'ifne': -1, 'iflt': -1, 'ifle': -1, 'ifgt': -1, 'ifge': -1,
        'if_icmpeq': -2, 'if_icmpne': -2, 'if_icmplt': -2,
        'if_icmple': -2, 'if_icmpgt': -2, 'if_icmpge': -2,
        'fcmpg': -1, 'goto': 0, 'lookupswitch': -1,
        'invokestatic': 0, 'invokespecial': 0,
        'invokevirtual': 0, 'invokenonvirtual': 0,
        'return': 0, 'ireturn': -1, 'freturn': -1, 'areturn': -1,
        'nop': 0
    }